name: flutter_daily_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  table_calendar: ^3.1.2
  provider: ^6.1.2

  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.3
  flutter_timezone: ^1.0.8
  

    



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
